apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  selector:
    matchLabels:
      app: demo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: huy8895/demo-cicd-github
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          #  kubectl create secret generic demo-secret --from-literal=SPRING_APPLICATION_NAME="demo from secret"
          envFrom:
            - secretRef:
                name: demo-secret
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: ClusterIP
  selector:
    app: demo-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
