apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  selector:
    matchLabels:
      app: demo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: huy8895/demo-cicd-github
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
          env: # Thêm mục này
            - name: SPRING_APPLICATION_NAME
              value: "demo-service"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: ClusterIP
  selector:
    app: demo-service
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
