
server:
  port: 8090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /${segment}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          routes:
            - id: account-service-route
              uri: lb://account-service
              predicates:
                - Path=/account/**

